version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  assignees:
  - acdibble
  ignore:
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
  rebase-strategy: disabled
