name: Build bot

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Elixir
      uses: actions/setup-elixir@v1.2.0
      with:
        otp-version: 22
        elixir-version: 1.10.3
        install-hex: true
        install-rebar: false

    - name: Install dependencies
      run: mix deps.get

    - name: Build release
      run: MIX_ENV=prod mix release
      env:
        PORT: ${{ secrets.PORT }}
        SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
        SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}

    - name: Package release
      run: tar -czvf bot.tar.gz -C _build/prod/rel/ code_bro_bot

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: bot.tar.gz
        path: bot.tar.gz
